[package]
name = "reia_gdext"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.

[dependencies]
godot = "0.2.4"
godot_tokio = "0.3.0"
sustenet = { version = "0.1.1", features = ["full"] }
tokio = { version = "1.44.2", features = ["sync"] }
