[package]
name = "reia_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
postgrest = "1.0"  # Supabase Rust client
supabase-auth = "0.4"  # Supabase Auth client
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = [] }  # Updated to remove full features
jwt = "0.16"  # For handling Supabase JWTs
