name: Rust Test

on:
  workflow_dispatch:
  push:
    paths:
      - rust/**

jobs:
  rust:
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Placeholder
        run: echo "TODO"
